// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVihvrUt4BFqOvAZoohK9IGHAVaExbXQ8',
    appId: '1:205752804443:web:05d8cba8eb58a1ff460b7e',
    messagingSenderId: '205752804443',
    projectId: 'closetapp-b941f',
    authDomain: 'closetapp-b941f.firebaseapp.com',
    databaseURL: 'https://closetapp-b941f-default-rtdb.firebaseio.com',
    storageBucket: 'closetapp-b941f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpth5zAh6N_-5tZ49ZgeSsSpSNHt48G0',
    appId: '1:205752804443:ios:065af682b5a0af27460b7e',
    messagingSenderId: '205752804443',
    projectId: 'closetapp-b941f',
    databaseURL: 'https://closetapp-b941f-default-rtdb.firebaseio.com',
    storageBucket: 'closetapp-b941f.firebasestorage.app',
    iosBundleId: 'com.example.startapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVihvrUt4BFqOvAZoohK9IGHAVaExbXQ8',
    appId: '1:205752804443:web:b486ea5a88d49aad460b7e',
    messagingSenderId: '205752804443',
    projectId: 'closetapp-b941f',
    authDomain: 'closetapp-b941f.firebaseapp.com',
    databaseURL: 'https://closetapp-b941f-default-rtdb.firebaseio.com',
    storageBucket: 'closetapp-b941f.firebasestorage.app',
  );
}
